version: "3.2"
services:
  warrior:
    container_name: warrior
    image: archiveteam/warrior-dockerfile:latest
    mac_address: ${WARRIORMAC}
    networks:
      homebridge:
        ipv4_address: ${WARRIORIP}
    environment:
     - DOWNLOADER=${HTTP_USERNAME}
     - SELECTED_PROJECT=auto
     - SHARED_RSYNC_THREADS=20
     - CONCURRENT_ITEMS=3
    restart: always

networks:
  homebridge:
    external:
      name: homebridge