version: "3.2"
services:
  svn-server:
    container_name: svn-server
    image: elleflorio/svn-server:latest
    mac_address: ${SVNMAC}
    networks:
      homebridge:
        ipv4_address: ${SVNIP}
    volumes:
     - ./config/:/etc/subversion
     - /volume1/svn/:/home/svn
    restart: unless-stopped

networks:
  homebridge:
    external:
      name: homebridge
