version: "3.2"
services:
  traefik:
    hostname: traefik
    image: traefik:latest
    container_name: traefik
    restart: always
    domainname: ${DOMAINNAME}
    networks:
      traefik_proxy:
      homebridge:
        ipv4_address: ${DOCKERNETWORKIP}
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"  
      # - "traefik.frontend.rule=Host:${DOMAINNAME}; PathPrefixStrip: /traefik"  
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=false"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
      # - "traefik.frontend.auth.basic=${HTTP_USERNAME}:${HTTP_PASSWORD}"
      - "traefik.frontend.auth.basic=/shared/.htpasswd"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${USERDIR}/docker/traefik/config:/etc/traefik
      - ${USERDIR}/docker/traefik/shared:/shared

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  homebridge:
    external:
      name: ${DOCKERNETWORK}
